### Logistic Regression

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r"C:\Users\sujat\Downloads\Moneypox.csv")
data

Patient_ID     Systemic Illness  Rectal Pain  Sore Throat  \
0             P0                 None        False         True   
1             P1                Fever         True        False   
2             P2                Fever        False         True   
3             P3                 None         True        False   
4             P4  Swollen Lymph Nodes         True         True   
...          ...                  ...          ...          ...   
24995     P24995                 None         True         True   
24996     P24996                Fever        False         True   
24997     P24997                 None         True         True   
24998     P24998  Swollen Lymph Nodes        False         True   
24999     P24999  Swollen Lymph Nodes        False        False   

       Penile Oedema  Oral Lesions  Solitary Lesion  Swollen Tonsils  \
0               True          True            False             True   
1               True          True            False            False   
2               True         False            False            False   
3              False         False             True             True   
4               True         False            False             True   
...              ...           ...              ...              ...   
24995          False          True             True            False   
24996           True         False             True             True   
24997          False         False             True             True   
24998          False          True             True             True   
24999           True         False            False             True   

       HIV Infection  Sexually Transmitted Infection MonkeyPox  
0              False                           False  Negative  
1               True                           False  Positive  
2               True                           False  Positive  
3               True                           False  Positive  
4               True                           False  Positive  
...              ...                             ...       ...  
24995          False                            True  Positive  
24996           True                            True  Positive  
24997          False                           False  Positive  
24998          False                           False  Negative  
24999           True                           False  Positive  

[25000 rows x 11 columns]

In [3]:
data.isnull().sum()

Patient_ID                        0
Systemic Illness                  0
Rectal Pain                       0
Sore Throat                       0
Penile Oedema                     0
Oral Lesions                      0
Solitary Lesion                   0
Swollen Tonsils                   0
HIV Infection                     0
Sexually Transmitted Infection    0
MonkeyPox                         0
dtype: int64

In [4]:
data["MonkeyPox"].value_counts()

Positive    15909
Negative     9091
Name: MonkeyPox, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
d1=LabelEncoder()
data["Systemic Illness"]=d1.fit_transform(data["Systemic Illness"])
data["Rectal Pain"]=d1.fit_transform(data["Rectal Pain"])
data["Penile Oedema"]=d1.fit_transform(data["Penile Oedema"])
data["Oral Lesions"]=d1.fit_transform(data["Oral Lesions"])
data["Solitary Lesion"]=d1.fit_transform(data["Solitary Lesion"])
data["HIV Infection"]=d1.fit_transform(data["HIV Infection"])
data["Sexually Transmitted Infection"]=d1.fit_transform(data["Sexually Transmitted Infection"])
data["MonkeyPox"]=d1.fit_transform(data["MonkeyPox"])
data["Sore Throat"]=d1.fit_transform(data["Sore Throat"])
data["Swollen Tonsils"]=d1.fit_transform(data["Swollen Tonsils"])
data["Patient_ID"]=d1.fit_transform(data["Patient_ID"])

In [6]:
data

Patient_ID  Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
0               0                 2            0            1              1   
1               1                 0            1            0              1   
2           11112                 0            0            1              1   
3           17223                 2            1            0              0   
4           18334                 3            1            1              1   
...           ...               ...          ...          ...            ...   
24995       16663                 2            1            1              0   
24996       16664                 0            0            1              1   
24997       16665                 2            1            1              0   
24998       16666                 3            0            1              0   
24999       16667                 3            0            0              1   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
0                 1                0                1              0   
1                 1                0                0              1   
2                 0                0                0              1   
3                 0                1                1              1   
4                 0                0                1              1   
...             ...              ...              ...            ...   
24995             1                1                0              0   
24996             0                1                1              1   
24997             0                1                1              0   
24998             1                1                1              0   
24999             0                0                1              1   

       Sexually Transmitted Infection  MonkeyPox  
0                                   0          0  
1                                   0          1  
2                                   0          1  
3                                   0          1  
4                                   0          1  
...                               ...        ...  
24995                               1          1  
24996                               1          1  
24997                               0          1  
24998                               0          0  
24999                               0          1  

[25000 rows x 11 columns]

In [7]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [8]:
from imblearn.over_sampling import RandomOverSampler
r1=RandomOverSampler()
x_data,y_data=r1.fit_resample(x,y)

In [9]:
from collections import Counter
print(Counter(y_data))

Counter({0: 15909, 1: 15909})


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)

In [11]:
print(Counter(y_train))

Counter({1: 12730, 0: 12724})


## LogisticRegression

In [12]:
from sklearn.linear_model import LogisticRegression
l1=LogisticRegression()
l1.fit(x_train,y_train)

LogisticRegression()

In [13]:
y_pred=l1.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)*100
print(acc)

50.047140163419236


## With Corss-validation

In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=11,shuffle=True)
kf.get_n_splits(x)

5

In [16]:
scores=cross_val_score(l1,x_train,y_train,cv=kf)
y_pred=cross_val_predict(l1,x_test,y_test)
print(Counter(y_test))
print(scores)
print(y_pred)

Counter({0: 3185, 1: 3179})
[0.49381261 0.59831074 0.49852681 0.57198979 0.58388998]
[0 1 1 ... 1 0 1]
